// Package poses defines the 16-joint billboard rig and the baked animation
// pose tables generated by cmd/animconv.
package poses

import (
	"math"

	"github.com/go-gl/mathgl/mgl64"
)

type Joint int

const (
	JPelvis Joint = iota
	JSpine
	JNeck
	JHead
	JThighL
	JShinL
	JFootL
	JThighR
	JShinR
	JFootR
	JUpperArmL
	JForearmL
	JHandL
	JUpperArmR
	JForearmR
	JHandR
	JointCount
)

// Pose holds the (u,v) billboard-plane position of every joint.
type Pose [JointCount]mgl64.Vec2

// Lerp linearly interpolates each joint between poses a and b.
func Lerp(a, b Pose, t float64) Pose {
	var out Pose
	for i := range out {
		out[i] = mgl64.Vec2{
			a[i][0] + (b[i][0]-a[i][0])*t,
			a[i][1] + (b[i][1]-a[i][1])*t,
		}
	}
	return out
}

// Clip is a baked keyframe animation generated by cmd/animconv: a sequence of
// poses sampled by phase. Entities load whichever clips they need per event.
type Clip []Pose

// Sample returns the pose at the given phase, looping seamlessly across the
// last frame back to the first.
func (c Clip) Sample(phase float64) Pose {
	n := len(c)
	if n == 0 {
		return Pose{}
	}
	f := (phase - math.Floor(phase)) * float64(n)
	i := int(f)
	if i >= n {
		i = n - 1
	}
	return Lerp(c[i], c[(i+1)%n], f-float64(i))
}
